version: '3.8'

services:
  mysql_db:
    image: mysql
    restart: always
    cap_add:
      - SYS_NICE
    volumes:
      - "./setup.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./books.sql:/docker-entrypoint-initdb.d/2.sql"
      - "./data.sql:/docker-entrypoint-initdb.d/3.sql"
    ports:
      - "9906:3306"
    environment:
      MYSQL_DATABASE: books
      MYSQL_ROOT_PASSWORD: password 
      MYSQL_HOST: localhost

  backend:
    build: 
      dockerfile: Dockerfile
      context: ./backend
    volumes:
      - /app/node_modules
      - ./backend:/app
    ports:
      - 3001:3001

  frontend:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./frontend
    ports:
      - 3000:3000

  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - mysql_db
    environment:
      ADMINER_DEFAULT_SERVER: mysql_db
